[package]
name = "concurrency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
futures = "0.3.28"
tokio = { version = "1.31.0", features = ["full"] }
reqwest = "0.11.18"
anyhow = "1.0.74"
