[package]
name = "iron-gcd"
version = "0.1.0"
authors = ["fernal73 <linus.fernandes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.1"
mime = "0.3.17"
router = "0.6.0"
urlencoded = "0.6.0"
